DROP DATABASE IF EXISTS INVENTORY;

CREATE DATABASE INVENTORY CHARACTER SET utf8 COLLATE utf8_general_ci;

USE INVENTORY;
SET SQL_SAFE_UPDATES = 0;

CREATE TABLE INVENTORY_DEALERS (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE INVENTORY_PRODUCTS (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(500) NOT NULL,
    `price` INT NOT NULL,
    `brand` VARCHAR(500) NOT NULL,
    `cod` VARCHAR(500) NOT NULL,
    `dealer_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`dealer_id`) REFERENCES INVENTORY_DEALERS(`id`) ON DELETE CASCADE
);

CREATE TABLE INVENTORY_CHANGE_LOG (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `old_quantity` INT NOT NULL,
    `new_quantity` INT NOT NULL,
    `change_date` DATETIME NOT NULL,
    `product_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`product_id`) REFERENCES INVENTORY_PRODUCTS(`id`) ON DELETE CASCADE
);
